### ISSUE TITLE
File names are formatted wrong

### ISSUE THREAD

**Issue by MoTem** [aliparlakci/bulk-downloader-for-reddit#66] opened 2019-10-02 21:53 UTC
They are not following the file name format from the documentation and look like random gibberish. Maybe a back end API update from Reddit's side messed it up.

**Comment by aliparlakci** [comment] 2019-10-02 22:05
Can you explain it with examples? I nearly forgot the code base. But it was runnig smooth last time i checked. It is highly likely that reddit has changed its API.

**Comment by MoTem** [comment] 2019-10-02 22:12
Sorry I accidentally closed it. Here are is an example:

Reddit Title "Life is too short to be a chump. The 80/20 rule isn't a theory, it is law. Not every action yields an equal result. The key to personal success is finding the 20% of things that give you 80% of your results and to double down on those motherfuckers. Here is a guide."

https://www.reddit.com/r/TheRedPill/comments/7ykxcy/life_is_too_short_to_be_a_chump_the_8020_rule/

Bulk Downloader title - 7ykxcy.md

Just to note, it does work on 90% of the posts I tried on (I downloaded 1000). But it fails in some cases.

**Comment by aliparlakci** [comment] 2019-10-02 22:22
Oh. This is not a bug. Windows throws an error if a file's directory is too
long (with the name at the end) and the program crashes. So, i cut down the
filename whenever this happens. Close the issue if you are satisfied,
please.

Thank you for using my script. You are the best.

**Closed** 2019-10-02 22:30 UTC
