### ISSUE TITLE
[BUG] Tool crashes filename too long

### ISSUE THREAD

**Issue by BeachNL** [aliparlakci/bulk-downloader-for-reddit#718] opened 2022-12-12 11:09 UTC
- [ X] I am reporting a bug.
- [ X I am running the latest version of BDfR
- [ X] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

Traceback (most recent call last):
  File "/Users/roy/Library/Python/3.9/bin/bdfr", line 8, in <module>
    sys.exit(cli())
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/bdfr/__main__.py", line 91, in cli_download
    reddit_downloader.download()
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/bdfr/downloader.py", line 47, in download
    self._download_submission(submission)
  File "/Users/roy/Library/Python/3.9/lib/python/site-packages/bdfr/downloader.py", line 105, in _download_submission
    if destination.exists():
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1414, in exists
    self.stat()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
OSError: [Errno 63] File name too long:

## Command

cat Subreddits.txt | xargs -L 1 echo --subreddit | xargs -L 50 bdfr download /Volumes/Adult/Web/Reddit/Subreddits --no-dupes --search-existing --skip txt

## Environment (please complete the following information)

- OS: MacOS Ventura
- Python version: 3.9

**Comment by Serene-Arc** [comment] 2022-12-12 12:27
I'm guessing that this is a duplicate of #656. It looks like you're downloading to an external volume @BeachNL, is this the case? Either a network drive or a HDD with a different filesystem.

The issue is that the BDFR can't tell what filesystem you're writing to, only what the OS is. We configure the path lengths based on the OS but with Mac/Linux, they are more permissive (better) than other filesystems, so this error happens because you're basically tricking the BDFR into thinking the files can be a certain length when they can't.

**Comment by BeachNL** [comment] 2022-12-12 12:28
> 

It is writing on a SMB network share

**Comment by Serene-Arc** [comment] 2022-12-12 12:29
Yes this is a duplicate then. I'll close it, please see the other thread for updates on this issue as it's resolved.

**Closed by Serene-Arc** 2022-12-12 12:29 UTC
Labels: bug, duplicate
