### ISSUE TITLE
[BUG] Application crashes on attempting to download a "saved removed submission"

### ISSUE THREAD

**Issue by bauermaximilian** [aliparlakci/bulk-downloader-for-reddit#511] opened 2021-08-21 15:15 UTC
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
When downloading the submissions saved in my reddit profile, the application repeatedly crashes on attempting to download a post which has been removed from the original subreddit by its moderator.

## Command
```
python -m bdfr download ./downloads --user me --saved --authenticate --file-scheme "{POSTID} {SUBREDDIT} {REDDITOR} {TITLE}"
```

## Environment
 - OS: Windows 10 Pro (Build 19043)
 - Python version: 3.9.6

## Logs
```
[2021-08-21 16:34:06,498 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 81, in cli_download
    reddit_downloader.download()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 73, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\site_downloaders\gallery.py", line 23, in find_resources
    image_urls = self._get_links(self.post.gallery_data['items'])
TypeError: 'NoneType' object is not subscriptable
```

## Additional notes
I apologize that I can not provide the Reddit ID for the submission which caused the crash - the described issue could be (temporarily) fixed by just changing the line 24 in the file ``gallery.py`` to ``except (AttributeError, TypeError):`` though.

**Comment by ErikLentz** [comment] 2021-08-24 14:41
I encountered the same bug just now, and your temporary fix worked for me.

**Comment by Serene-Arc** [comment] 2021-08-25 00:18
@ErikLentz can you provide the submission ID that caused the issue? I need that to write tests to ensure the problem is fixed

**Comment by sevenzk** [comment] 2021-09-01 09:35
Thanks for the additional notes, works for me when adding the line you wrote.

**Comment by Serene-Arc** [comment] 2021-09-03 06:41
This issue is already fixed on the development branch

**Closed by Serene-Arc** 2021-09-03 06:41 UTC
Labels: bug
